#!/bin/bash

GREEN_BOLD="\e[1;32m"
RED_BOLD="\e[1;31m"
YELLOW_BOLD="\e[1;33m"
WHITE="\e[0;37m"
BLUE_BOLD="\e[1;34m"
GREEN_BOLD="\e[1;32m"
COLOR_OFF="\e[0m"

function info {
	echo -e " ${GREEN_BOLD}* ${COLOR_OFF}${1}"
}

function error {
	echo -e " ${RED_BOLD}* ${COLOR_OFF}${1}"
}

function warning {
	echo -e " ${YELLOW_BOLD}* ${COLOR_OFF}${1}"
}

function __usage {
	echo "Usage: $(basename $0) [OPTIONS] PREFIX OVERLAY [CATEGORY_PACKAGE]"
	echo "Download overlay, category or package ebuilds from gpo.zugaina.org"
	echo ""
	echo "    PREFIX               destination of downloaded files"
	echo "    OVERLAY              name of overlay"
	echo "    CATEGORY_PACKAGE     category or category/package that you want download"
	echo ""
	echo "OPTIONS:"
	echo "    -v, --verbose   tree print of downloaded files"
	echo "    -p, --pretend   display what will downloaded"
	echo "    -h, --help      display this help and exit"
	echo ""
	echo "Examples:"
	echo "    $(basename $0) my_prefix_dir kde                      ->  for download all ebuilds from kde overlay" 
	echo "    $(basename $0) my_prefix_dir kde kde-misc             ->  for download kde-misc category ebuilds from kde overlay"
	echo "    $(basename $0) my_prefix_dir kde kde-misc/kdeconnect  ->  for download all kdeconnect package ebuilds from kde overlay"
    exit 1
}

function __get_list {
	curl -sL "${1}" | grep -v Parent | awk 'BEGIN{
	RS="</a>"
	IGNORECASE=1
	}
	{
	for(o=1;o<=NF;o++){
		if ( $o ~ /href/){
		gsub(/.*href=\042/,"",$o)
		gsub(/\042.*/,"",$o)
		print $(o)
		}
	}
	}'
}

function __check_eclass {
	local RES=""
	
	if [[ "${1}" == *.ebuild ]]; then
		local LIST=$(curl -s "${1}" | grep inherit -A1 | sed 's/inherit//;s/\\//')
		
		for ECLASS in ${LIST}; do
			if [ ! -f /usr/portage/eclass/"${ECLASS}.eclass" ]; then
				#[ ! -d "${PREFIX%/}/eclass" ] && mkdir "${PREFIX%/}/eclass"
				#curl -s "${URL%/}/${OVERLAY%/}/eclass/${ECLASS}.eclass" -o "${PREFIX%/}/eclass/${ECLASS}.eclass"
				RES="${RES} ${ECLASS}.eclass"
			fi
		done;
	fi
	echo "${RES}"
}

function __curl {
	[ $DRY_RUN -eq 0 ] && curl $@
}

function __mkdir {
	[ $DRY_RUN -eq 0 ] && mkdir $@
}

function __get_eclass {
	[ ! -d "${PREFIX%/}/eclass" ] && __mkdir "${PREFIX%/}/eclass"
	if [[ ${VERBOSE} -eq 1 ]]; then
		echo "|-- eclass"
	fi
	for ECLASS in ${ECLASSES}; do
		if [[ ${VERBOSE} -eq 1 ]]; then
			echo "|   |-- ${ECLASS}"
		fi
		__curl -s "${URL%/}/${OVERLAY%/}/eclass/${ECLASS}" -o "${PREFIX%/}/eclass/${ECLASS}"
	done;
}

function __print {
	if [[ ${VERBOSE} -eq 1 ]]; then
		local CATEGORY_PACKAGE="${1/$PREFIX/}"
		local OCCURENCE=$(echo ${CATEGORY_PACKAGE%/} | tr -cd '/' | wc -c)
		local TREE="|--"
		
		if [[ $((OCCURENCE - $IS_PACKAGE)) -gt 0 ]]; then
			for i in $(seq 0 $((OCCURENCE - 0))); do
				TREE="|   ${TREE}"
			done
		elif [[ ${IS_PACKAGE} -eq 1 ]]; then
			echo -e "${TREE} $(dirname ${CATEGORY_PACKAGE})"
			TREE="|   ${TREE}"
		fi
		
		echo -e "${TREE} $(basename ${CATEGORY_PACKAGE})"
	fi
}

function __get_files_rec {
	local URL="${1}"
	local MYPATH="${2}"
	
	[[ "${MYPATH%/}" != "${PREFIX%/}" ]] && __print "${MYPATH%/}" 
	for FILE in $(__get_list ${URL}); do
		local IS_DIR=$(curl -s -I "${URL%/}/${FILE}" | grep "^Content-Type: text/html")
		if [[ -z "${IS_DIR// }" ]]; then
			__curl -s "${URL%/}/${FILE}" -o "${MYPATH%/}/${FILE}"
			__print "${MYPATH%/}/${FILE}" 
			ECLASSES="${ECLASSES} $(__check_eclass "${URL%/}/${FILE}")" #"${MYPATH%/}/${FILE}")"
		else
 			__mkdir -p "${MYPATH%/}/${FILE}"
			__get_files_rec "${URL%/}/${FILE}" "${MYPATH%/}/${FILE}"
		fi
	done
	

}

[ $# -eq 0 ] && __usage
SHORT="hvp"
LONG="help,verbose,pretend"

PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
eval set -- "$PARSED"

OPT_NUM=0
VERBOSE=0
DRY_RUN=0
while true; do
  case "${1}" in
	-p|--pretend)
		VERBOSE=1
		DRY_RUN=1
		OPT_NUM=$((OPT_NUM+1))
		break
		;;
	-v|--verbose)
		VERBOSE=1
		OPT_NUM=$((OPT_NUM+1))
		break
		;;
	-h|--help) 
		__usage
		exit 0
		;;
	*) 
		break
		;;
  esac
  
done

PREFIX="${@:$((OPT_NUM+2)):1}"
PREFIX="${PREFIX%/}/"
OVERLAY="${@:$((OPT_NUM+3)):1}"
PACKAGE="${@:$((OPT_NUM+4)):1}"

URL="http://data.gpo.zugaina.org/"
ECLASSES=""

if [ -z "${PREFIX}" ] || [ -z "${OVERLAY}" ]; then
	__usage
	exit 0
fi

if [ ! -d "${PREFIX}" ]; then 
	error "Prefix directory \"${PREFIX}\" not exists" 
	exit 1
else
	USER_PREFIX=$(stat -c %U ${PREFIX})
	if [[ "$USER_PREFIX" != $(whoami) ]]; then
		warning "Prefix ${PREFIX} need root permission" 
		exit 1
	fi
fi

if [ $(curl -s -o /dev/null -w "%{http_code}" "${URL%/}/${OVERLAY}") -eq 404 ]; then
	error "Overlay $OVERLAY not exists"
	exit 1
fi

if [ $(curl -s -o /dev/null -w "%{http_code}" "${URL%/}/${OVERLAY%/}/${PACKAGE}") -eq 404 ]; then
	error "Category or package $PACKAGE not exists"
	exit 1
fi

[ "$(echo ${PACKAGE%/} | tr -cd '/' | wc -c)" -gt 0 ] && IS_PACKAGE=1 || IS_PACKAGE=0
__mkdir -p "${PREFIX%/}/${PACKAGE}"
__get_files_rec "${URL%/}/${OVERLAY%/}/${PACKAGE}" "${PREFIX%/}/${PACKAGE}"
ECLASSES=$(echo $ECLASSES | xargs -n1 | sort -u | xargs)
[ ! -z "${ECLASSES}" ] && [ ! -z "${PACKAGE}" ] && __get_eclass
